In [1]:
from keras.models import Sequential
from keras.layers import Dense

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
seed = 777
np.random.seed(seed)

In [4]:
tf.set_random_seed(seed)

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('data/DeepLearning_Data/Seoul_Vacancy_Rate_v4.csv', encoding= 'ansi')

In [7]:
from sklearn.model_selection import train_test_split

In [9]:
x_data = df.iloc[:, :-1]
x_data.head()

   총_유동인구_수  남성_유동인구_수  여성_유동인구_수  남성_상주인구_수  여성_상주인구_수  ...  여성_매출_금액  주중_매출_건수  주말_매출_건수       점포수    임대료_전체
0 -0.382941  -0.395933  -0.367207  -0.873870  -0.834053  ... -0.269315 -0.298673 -0.249881 -0.260075 -0.066647
1 -0.219401  -0.204411  -0.231816  -0.929033  -0.878505  ... -0.149443 -0.097132 -0.080064 -0.185178 -0.066647
2  0.489636   0.598670   0.381259   0.116235   0.362101  ...  0.379810  1.258679  0.332590  1.425124 -0.066647
3 -0.548467  -0.573487  -0.519811  -0.904987  -0.847524  ... -0.349983 -0.471186 -0.415728 -0.504594 -0.066647
4 -0.010546   0.029175  -0.048392  -1.368922  -1.374209  ... -0.215621  0.094473 -0.227681 -0.271090 -0.066647

[5 rows x 42 columns]

In [10]:
y_data = df.iloc[:, -1:]
y_data.head()

   공실률
0  1.8
1  1.8
2  1.8
3  1.8
4  1.8

In [11]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size= 0.3,
                                                   random_state= seed)

In [13]:
X_train.shape

(2039, 42)

In [22]:
model = Sequential()

In [24]:
model.add(Dense(24, input_dim= 42, activation= 'relu'))

In [25]:
model.add(Dense(10, activation= 'relu'))

In [26]:
model.add(Dense(10, activation= 'relu'))

In [27]:
model.add(Dense(1))

In [29]:
model.compile(loss= 'mean_squared_error', optimizer= 'adam')

In [30]:
model.fit(X_train, y_train, epochs= 50, batch_size= 5)

Epoch 1/50
2039/2039 [==============================] - 2s 811us/step - loss: 27.6156
Epoch 2/50
2039/2039 [==============================] - 1s 727us/step - loss: 17.9492
Epoch 3/50
2039/2039 [==============================] - 2s 736us/step - loss: 16.4650
Epoch 4/50
2039/2039 [==============================] - 2s 737us/step - loss: 15.5250
Epoch 5/50
2039/2039 [==============================] - 1s 735us/step - loss: 14.7120
Epoch 6/50
2039/2039 [==============================] - 1s 735us/step - loss: 13.9999
Epoch 7/50
2039/2039 [==============================] - 2s 736us/step - loss: 13.4464
Epoch 8/50
2039/2039 [==============================] - 1s 729us/step - loss: 12.5633
Epoch 9/50
2039/2039 [==============================] - 1s 735us/step - loss: 12.2001
Epoch 10/50
2039/2039 [==============================] - 2s 752us/step - loss: 11.4395
Epoch 11/50
2039/2039 [==============================] - 2s 751us/step - loss: 10.9586
Epoch 12/50
2039/2039 [==============================] - 2s 751us/step - loss: 10.6579
Epoch 13/50
2039/2039 [==============================] - 2s 739us/step - loss: 10.0109
Epoch 14/50
2039/2039 [==============================] - 2s 746us/step - loss: 9.7804
Epoch 15/50
2039/2039 [==============================] - 1s 735us/step - loss: 9.4684
Epoch 16/50
2039/2039 [==============================] - 2s 743us/step - loss: 9.2395
Epoch 17/50
2039/2039 [==============================] - 2s 743us/step - loss: 8.8614
Epoch 18/50
2039/2039 [==============================] - 2s 752us/step - loss: 8.5260
Epoch 19/50
2039/2039 [==============================] - 2s 747us/step - loss: 8.5871
Epoch 20/50
2039/2039 [==============================] - 2s 751us/step - loss: 8.3468
Epoch 21/50
2039/2039 [==============================] - 2s 753us/step - loss: 8.1561
Epoch 22/50
2039/2039 [==============================] - 2s 752us/step - loss: 7.8897
Epoch 23/50
2039/2039 [==============================] - 2s 753us/step - loss: 7.9568
Epoch 24/50
2039/2039 [==============================] - 2s 751us/step - loss: 7.6005
Epoch 25/50
2039/2039 [==============================] - 2s 751us/step - loss: 7.5408
Epoch 26/50
2039/2039 [==============================] - 2s 773us/step - loss: 7.3843
Epoch 27/50
2039/2039 [==============================] - 2s 756us/step - loss: 7.1999
Epoch 28/50
2039/2039 [==============================] - 2s 746us/step - loss: 7.1169
Epoch 29/50
2039/2039 [==============================] - 2s 782us/step - loss: 7.1733
Epoch 30/50
2039/2039 [==============================] - 2s 767us/step - loss: 6.8992
Epoch 31/50
2039/2039 [==============================] - 2s 751us/step - loss: 6.7943
Epoch 32/50
2039/2039 [==============================] - 2s 757us/step - loss: 6.6609
Epoch 33/50
2039/2039 [==============================] - 2s 757us/step - loss: 6.6410
Epoch 34/50
2039/2039 [==============================] - 2s 754us/step - loss: 6.4888
Epoch 35/50
2039/2039 [==============================] - 2s 756us/step - loss: 6.3454
Epoch 36/50
2039/2039 [==============================] - 2s 762us/step - loss: 6.3995
Epoch 37/50
2039/2039 [==============================] - 2s 744us/step - loss: 6.2722
Epoch 38/50
2039/2039 [==============================] - 2s 746us/step - loss: 6.0910
Epoch 39/50
2039/2039 [==============================] - 2s 743us/step - loss: 6.1099
Epoch 40/50
2039/2039 [==============================] - 2s 748us/step - loss: 6.0074
Epoch 41/50
2039/2039 [==============================] - 2s 754us/step - loss: 5.9099
Epoch 42/50
2039/2039 [==============================] - 2s 761us/step - loss: 5.9187
Epoch 43/50
2039/2039 [==============================] - 2s 754us/step - loss: 5.8258
Epoch 44/50
2039/2039 [==============================] - 2s 770us/step - loss: 5.9313
Epoch 45/50
2039/2039 [==============================] - 2s 769us/step - loss: 5.6433
Epoch 46/50
2039/2039 [==============================] - 2s 752us/step - loss: 5.5444
Epoch 47/50
2039/2039 [==============================] - 2s 770us/step - loss: 5.5113
Epoch 48/50
2039/2039 [==============================] - 2s 761us/step - loss: 5.4179
Epoch 49/50
2039/2039 [==============================] - 2s 764us/step - loss: 5.4751
Epoch 50/50
2039/2039 [==============================] - 2s 764us/step - loss: 5.3053

In [50]:
Y_predicion = model.predict(X_test).flatten()

In [51]:
a = y_test.values
a[1,0]

11.4

In [53]:
for i in range(20):
    label = a[i, 0]
    prediction = Y_predicion[i]
    print('{:.3f}, ==== {:.3f}'.format(label, prediction))

5.000, ==== 7.132
11.400, ==== 9.123
3.800, ==== 4.841
7.500, ==== 6.370
5.900, ==== 5.849
9.600, ==== 7.947
9.300, ==== 8.843
2.500, ==== 7.046
2.500, ==== 7.164
5.300, ==== 8.312
2.800, ==== 5.813
11.200, ==== 8.162
2.500, ==== 6.485
4.700, ==== 4.874
14.900, ==== 17.341
7.600, ==== 7.512
7.500, ==== 9.361
2.900, ==== 8.483
12.800, ==== 11.732
5.700, ==== 4.764